"""create all tables

Revision ID: 229b9e2a7344
Revises: 30f089237800
Create Date: 2025-10-19 14:59:20.329930+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229b9e2a7344'
down_revision = '30f089237800'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
