name: evolucaofit-app
region: atl

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

features:
  - buildpack-stack=ubuntu-22

databases:
  - name: evolucaofit-db
    engine: PG
    version: "16"
    production: false
    cluster_name: evolucaofit-db-cluster

jobs:
  - name: db-migrate
    kind: PRE_DEPLOY
    github:
      repo: rafaelmarzulo/evolucaofit
      branch: main
      deploy_on_push: true
    dockerfile_path: apps/backend/Dockerfile
    source_dir: apps/backend
    instance_size_slug: apps-s-1vcpu-1gb
    instance_count: 1
    run_command: alembic upgrade head
    envs:
      - key: DATABASE_URL
        value: ${evolucaofit-db.DATABASE_URL}
        scope: RUN_TIME

services:
  - name: evolucaofit-apps-backend
    github:
      repo: rafaelmarzulo/evolucaofit
      branch: main
      deploy_on_push: true
    dockerfile_path: apps/backend/Dockerfile
    source_dir: apps/backend
    instance_size_slug: apps-s-1vcpu-1gb
    instance_count: 1
    http_port: 8000
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: DATABASE_URL
        value: ${evolucaofit-db.DATABASE_URL}
        scope: RUN_AND_BUILD_TIME
      - key: JWT_SECRET_KEY
        value: cOz9q0piDMoZePBjc0IBZjokKaiTL0olMWHDEu8KQqo
        scope: RUN_AND_BUILD_TIME
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "7"
      - key: CORS_CREDENTIALS
        value: "true"
      - key: ENABLE_METRICS
        value: "true"
      - key: RATE_LIMIT_PER_MINUTE
        value: "60"
      - key: RATE_LIMIT_LOGIN_PER_HOUR
        value: "5"

  - name: evolucaofit-apps-frontend
    github:
      repo: rafaelmarzulo/evolucaofit
      branch: main
      deploy_on_push: true
    dockerfile_path: apps/frontend/Dockerfile
    source_dir: apps/frontend
    instance_size_slug: apps-s-1vcpu-1gb
    instance_count: 1
    http_port: 3000
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: ${evolucaofit-apps-backend.PUBLIC_URL}
      - key: NEXT_PUBLIC_APP_URL
        value: ${APP_URL}

ingress:
  rules:
    - match:
        path:
          prefix: /api
      component:
        name: evolucaofit-apps-backend
    - match:
        path:
          prefix: /docs
      component:
        name: evolucaofit-apps-backend
    - match:
        path:
          prefix: /
      component:
        name: evolucaofit-apps-frontend
